### ISSUE TITLE
code_refactoring

### ISSUE THREAD

**Issue by sxnjorombe** [sxnjorombe/java_algorithms#3]
- [x] make a single class called **StringManipulation**
- [x] create two function one for palindromes and another for reverse
- [x] put the relevant logic in each of the palindrome and reverse functions. Let the palindrome function make use of reverse function and it should return true or false
- [x] reverse function should return a string that is the reverse of the inserted string
- [x] make another class you can call it whatever eg **JavaAlgorithms**, and it should have the main function. 
- [x] in the new class **JavaAlgorithm** create an instance of **StringManipulation** class. eg StringManipulation strManipulation = new StringManipulation();
- [x] call the functions palindrome and reverse from your **JavaAlgorithms** class

**Comment by abedyngash** [comment]
Quite Handy!

**Comment by abedyngash** [comment]
Okay, let me see into it
